### ISSUE TITLE
[Low priority] [UX] Confusing tokens on testnet

### ISSUE THREAD

**Issue by apollo-pablo** [wynddaoOld/dex-issue-tracker#27]
> Problem

When a user enter a pool `JUNOX/USDCX`, when **WYNNING** menu pop up and in the reference, its offers **UJUN/UUSD** which confuses about **JUNOX/USDCX** expected.
 
![image](https://user-images.githubusercontent.com/95628259/209703896-01765dce-f0c8-4a13-8979-3f163643ebe4.png)

> Tasks

- [ ] Fix asset list on testnet/ verify on mainnet.

**Comment by kyar1s** [comment]
Hi, I have been checking what we show here and there is actually no mistake with it. I don't know who created the pool, but I assume that being on testnet it was created with that name. What is happening is that the name of the pool is being displayed, which means that we don't do any transformation on how to display the data. So I suggest two options to come up with a solution: 

1. Don't show the pool name, but show the token names. 
2. When we are going to create the pool, or if it can be corrected afterwards, give it the correct name: JUNOX/USDCX. 

Personally, I think that the second option is the one that we should take, since this way it is not necessary to make any extra transformation in the front end, and also we give utility to the name that is given to the pool when it is created.

cc/ @apollo-pablo @WYNerD @abefernan
